### ISSUE TITLE
添加资源后，数据丢失

### ISSUE THREAD

**Issue by longlongwaytogo** [nandy007/gitdocument#1]
您好，
  当使用http://localhost:7700/mng/main.html， 从后台添加数据，填写完数据后保存。之后什么都没有了是怎么回事，是否需要其他配置。

控制台输出有些错误：

Starting child process with 'node ./app.js'
Watching directory 'F:\tmp\gitdocument-master' for changes.
Press rs for restarting the process.
the server is start at port 7700

  TypeError: fs.copyFileSync is not a function
      at exports.saveGit (F:\tmp\gitdocument-master\controllers\docs.js:114:8)
      at dispatch (F:\tmp\gitdocument-master\node_modules\koa-compose\index.js:4
4:32)
      at next (F:\tmp\gitdocument-master\node_modules\koa-compose\index.js:45:18
)
      at F:\tmp\gitdocument-master\node_modules\koa-router\lib\router.js:346:16
      at dispatch (F:\tmp\gitdocument-master\node_modules\koa-compose\index.js:4
4:32)
      at next (F:\tmp\gitdocument-master\node_modules\koa-compose\index.js:45:18
)
      at F:\tmp\gitdocument-master\node_modules\chestnut-router\index.js:91:15_

**Comment by nandy007** [comment]
我试了可以的，是否方便提供你的git地址给我试试

**Comment by nandy007** [comment]
查了下fs-extra的api如果需要支持copyFileSync函数可能需要你的node版本8.5.0+，你确认下node版本并尝试升级试试

链接https://github.com/jprichardson/node-fs-extra/blob/a32c85282185aa008759890cce059594e4348262/CHANGELOG.md#500--2017-12-11

**Comment by longlongwaytogo** [comment]
谢谢你的回复，我升级了下nodejs 到8.9版本，上传成功了（但是也有偶然失败的情形，上传后，gits/source目录下有上传的图片，但datacache.json没有数据），但无法查看到文档信息，提示：Internal Server Error。我只是fork了您的项目，作为学习，没有做什么修改：[https://github.com/longlongwaytogo/gitdocument](url).

不知道是否是我机器的问题。

**Comment by longlongwaytogo** [comment]
后来发现，将您主页的github仓库添加进去都可以显示，并且可以定位，我的github项目就不行。查看您的github项目中，都有docs目录，我的大多数没有，个别项目有docs目录，也无法显示 md文档。

**Comment by longlongwaytogo** [comment]
发现您的项目docs目录下都有一个index.json 里面的内容好像就是解析后页面的目录，应该是需要自己编写这个吧，但我试了下，也没成功？

**Comment by longlongwaytogo** [comment]
您好，已经可以使用了，把indexex.json看成index.json了。

**Comment by longlongwaytogo** [comment]
您好，请问这个项目，可以部署在github项目主页吗，本地上传数据后，上传到github是否可以。

**Comment by nandy007** [comment]
文档的目录固定是docs目录，并且需要docs目录下有index.json文件，这个文件就是你的文档的目录结构
暂时不能以项目主页为入口哦
